version: '{build}'
clone_depth: 10
environment:
  NVIM_NODE_LOG_LEVEL: debug

install:
  - ps: Install-Product node 8
  - node --version
  - npm --version
  - ps: |
      $zip = $Env:APPVEYOR_BUILD_FOLDER + '\nvim-win64.zip'
      $nvim = $Env:APPVEYOR_BUILD_FOLDER + '\nvim-win64\'
      $url = 'https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip'
      (New-Object Net.WebClient).DownloadFile($url, $zip)
      [Reflection.Assembly]::LoadWithPartialName('System.IO.Compression.FileSystem') > $null
      [System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $nvim)
      $Env:PATH = $Env:PATH + ';' + $nvim + '\Neovim\bin\'
  - echo %PATH%
  - nvim --version
  - npm install -g yarn
  - yarn global add codecov

build: off

test_script:
  - yarn
  - yarn link
  - yarn run prep-integration-test
  - yarn test -- --coverage

after_test:
  - codecov

deploy: off

notifications:
  - provider: Email
    on_build_status_changed: true
    on_build_success: false
    on_build_failure: false
