version: '{build}'
clone_depth: 10
environment:
  matrix:
    - NODE_VERSION: ""
      NVIM_NODE_LOG_LEVEL: debug
    - NODE_VERSION: "8"
      NVIM_NODE_LOG_LEVEL: debug

install:
  - ps: Install-Product node $Env:NODE_VERSION
  - node --version
  - npm --version
  - ps: |
      $zip = $Env:APPVEYOR_BUILD_FOLDER + '\nvim-win64.zip'
      $nvim = $Env:APPVEYOR_BUILD_FOLDER + '\nvim-win64\'
      $url = 'https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip'
      (New-Object Net.WebClient).DownloadFile($url, $zip)
      [Reflection.Assembly]::LoadWithPartialName('System.IO.Compression.FileSystem') > $null
      [System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $nvim)
      $Env:PATH = $Env:PATH + ';' + $nvim + '\Neovim\bin\'
  - echo %PATH%
  - nvim --version
  - npm install -g yarn
  - yarn global add codecov

build: off

test_script:
  - yarn
  - npm install -g . # provider#node#Detect() checks bin/cli.js directly. So symlink does not work (Issue #50)
  - yarn lerna run test-lint
  - yarn lerna run test-build

after_test:
  - codecov

deploy: off

notifications:
  - provider: Email
    on_build_status_changed: true
    on_build_success: false
    on_build_failure: false
