language: node_js
node_js: stable
cache: yarn

# required for allowed_failures
env: TEST_SUITE=test-missing-apis

# Use macOS 10.12: https://docs.travis-ci.com/user/languages/objective-c/
matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode9.1
      env: TEST_SUITE=test-build
    - os: linux
      dist: trusty
      env: TEST_SUITE=test-lint
    - os: linux
      dist: trusty
      env: TEST_SUITE=test-missing-apis
    - os: linux
      dist: trusty
      env: TEST_SUITE=test-build
  allow_failures:
    - language: node_js
      env: TEST_SUITE=test-missing-apis

jobs:
  include:
    stage: docs
      script: yarn doc

install:
  - npm install -g yarn
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
      tar xzf nvim-macos.tar.gz
      export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-osx64/bin"
    else
      curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
      tar xzf nvim-linux64.tar.gz
      export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-linux64/bin"
    fi
  - echo $PATH
  - nvim --version
  - yarn global add codecov
  - yarn

before_script:
  - yarn link
  - npm install -g ./

script:
  - export NVIM_NODE_LOG_LEVEL=debug
  - yarn $TEST_SUITE

after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: never
    on_cancel: never
    on_error: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7898b0d8d9ea3a28b496
    on_success: always
    on_failure: always
    on_cancel: always
    on_error: always
    on_start: never

deploy:
  local-dir: doc
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
