# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
- template: .azure-templates/yarn-job.yml  # Template reference
  parameters:
    name: 'Linux'
    vmImage: 'ubuntu-20.04'

- template: .azure-templates/yarn-job.yml  # Template reference
  parameters:
    name: 'macOS'
    vmImage: 'macOS-10.15'

- template: .azure-templates/yarn-job.yml  # Template reference
  parameters:
    name: 'Windows'
    vmImage: 'windows-2019'
